aider: Change ownership of fish config directory to vscode user during Docker build process.
# Aider chat conversation:

USER:
On opening the fish shell, getting the following errors. I'm guessing it's a permissions issue caused by how the config.fish file is being created during the docker build process.

error: Unable to open universal variable file '/home/vscode/.config/fish/fish_variables': Permission denied
error: Unable to open universal variable file '/home/vscode/.config/fish/fish_variables': Permission denied
error: Unable to open universal variable file '/home/vscode/.config/fish/fish_variables': Permission denied
error: Unable to open universal variable file '/home/vscode/.config/fish/fish_variables': Permission denied

ASSISTANT: To resolve this issue, we need to modify the Dockerfile to change the ownership of the /home/vscode/.config/fish directory to the vscode user. This will ensure that the vscode user has the necessary permissions to access and modify the fish_variables file.

Here is the *SEARCH/REPLACE* block:

.devcontainer/Dockerfile
```Dockerfile
<<<<<<< SEARCH
# Add poetry bin path to fish_user_paths and initiate starship
RUN mkdir -p /home/vscode/.config/fish && echo 'set -U fish_user_paths (poetry env info --path)/bin $fish_user_paths' >> /home/vscode/.config/fish/config.fish
RUN echo 'starship init fish | source' >> /home/vscode/.config/fish/config.fish
=======
# Add poetry bin path to fish_user_paths and initiate starship
RUN mkdir -p /home/vscode/.config/fish && chown -R vscode:vscode /home/vscode/.config/fish && echo 'set -U fish_user_paths (poetry env info --path)/bin $fish_user_paths' >> /home/vscode/.config/fish/config.fish
RUN echo 'starship init fish | source' >> /home/vscode/.config/fish/config.fish
>>>>>>> REPLACE
```

This change adds a chown command to change the ownership of the /home/vscode/.config/fish directory to the vscode user.